name: ThreeSquareMeals
description: Create nutritional meals instead of just soup
version: 0.1.0
author: Ben Sergent V

main: com.sergenttech.plugins.threesquaremeals.ThreeSquareMeals
database: false

permissions:
      
commands:
  threesquaremeals:
    description: Shows usage information for ThreeSquareMeals
    aliases: [nutrients,food,nut,meal]